# Generated by Django 4.2.7 on 2023-11-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='comment',
        ),
        migrations.AlterField(
            model_name='tickets',
            name='due_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='status',
            field=models.CharField(choices=[('re', 'Resolved'), ('un', 'Unresolved'), ('fr', 'Freezed')], default='un', max_length=16),
        ),
    ]
