# Generated by Django 4.2.7 on 2023-11-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_tickets_comment_alter_tickets_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='due_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
