# Generated by Django 4.2.7 on 2023-11-26 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_tickets_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='due_date',
            new_name='date',
        ),
    ]
