# Generated by Django 4.2.7 on 2023-11-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_tickets_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='owner',
            new_name='user',
        ),
    ]
