# Generated by Django 4.2.7 on 2023-11-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_rename_owner_tickets_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='status',
            field=models.CharField(choices=[('resolved', 'Resolved'), ('un', 'Unresolved'), ('fr', 'Freezed')], default='un', max_length=16),
        ),
    ]
