# Generated by Django 4.2.7 on 2023-11-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_tickets_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='status',
            field=models.CharField(choices=[('resolved', 'Resolved'), ('unresolved', 'Unresolved'), ('frezzed', 'Freezed')], default='unresolved', max_length=16),
        ),
    ]
