# Generated by Django 4.2.7 on 2023-12-03 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_tickets_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='message',
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.tickets'),
        ),
    ]
