# Generated by Django 4.2.7 on 2023-12-03 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_remove_tickets_message_alter_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.tickets'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
