# Generated by Django 4.2.7 on 2023-12-03 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_message_ticket_alter_message_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='ticket',
        ),
    ]
