# Generated by Django 4.2.7 on 2023-12-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_remove_message_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
