# Generated by Django 4.2.7 on 2023-12-03 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_alter_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.tickets'),
        ),
    ]
