# Generated by Django 4.2.7 on 2023-12-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_rename_message_messages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='messages',
            new_name='message',
        ),
    ]
