# Generated by Django 4.2.7 on 2023-12-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_rename_messages_messages_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='status',
            field=models.CharField(choices=[('resolved', 'Resolved'), ('unresolved', 'Unresolved'), ('freezed', 'Freezed')], default='unresolved', max_length=16),
        ),
    ]
